# Generated by Django 4.1.2 on 2022-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_bio_user_profilepicture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='None', max_length=24),
        ),
    ]
