# Generated by Django 4.1.2 on 2022-12-03 13:44

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_image_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.IntegerField(default=None, verbose_name=network.models.User),
        ),
    ]
