# Generated by Django 4.1.2 on 2022-12-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_caption_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='network/static/images'),
        ),
    ]
