# Generated by Django 4.1.2 on 2022-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='network/static/images'),
        ),
    ]
