# Generated by Django 4.1.2 on 2022-12-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
