# Generated by Django 4.1.2 on 2022-12-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
