# Generated by Django 4.1.2 on 2022-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
