# Generated by Django 4.1.2 on 2022-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='status',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='network/static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='network/static/images/'),
        ),
    ]
