# Generated by Django 4.1.2 on 2022-12-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_likes_status_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
