# Generated by Django 4.1.2 on 2022-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_realationships_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
